In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import scikit-learn 

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
my_data = pd.read_csv("data/drug200.csv", delimiter=",")
my_data[0:5]

In [ ]:
my_data.shape

In [ ]:
X = my_data[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
y = my_data["Drug"]

In [ ]:
print(X[0:5])
print(y[0:5])

### Tiền xử lý dữ liệu cho __X__ và __y__ để đưa về dạng số thực sử dụng các phương pháp:
- One-hot encoding cho trường thuộc tính thứ 2, 3, 4 của __X__
- Chuẩn hóa trường dữ liệu đầu tiên và cuối cùng của __X__ về khoảng (0, 1)
- Sử dụng One-hot encoding cho y
- Có thể tham khảo thư viện mã hóa one hot tại: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

In [ ]:
### YOUR CODE HERE ###

In [8]:
print(f'X_new.shape: {X_new.shape}')
print(f'y_new.shape: {y_new.shape}')
print(f'X_new[:, 0].min() = {X_new[:, 0].min()}')
print(f'X_new[:, 0].max() = {X_new[:, 0].max()}')
print(f'X_new[:, -1].min() = {X_new[:, -1].min()}')
print(f'X_new[:, -1].max() = {X_new[:, -1].max()}')
print("\n5 hàng đầu tiên của X và y:")
print(X_new[0:5, :])
print(y_new[0:5, :])

"""
Chú ý:
 - Việc mã hõa one-hot có thể khác nhau tùy theo cách quy ước.
 - Giá trị ở cột đầu tiên và cuối cùng của X_new là cố định
 - Mỗi dòng của mã hóa one hot ứng với một thuộc tính chỉ được phép có 1 số 1.
"""

X_new.shape: (200, 9)
y_new.shape: (200, 5)
X_new[:, 0].min() = 0.0
X_new[:, 0].max() = 1.0
X_new[:, -1].min() = 0.0
X_new[:, -1].max() = 1.0

5 hàng đầu tiên của X và y:
[[0.13559322 1.         0.         1.         0.         0.
  1.         0.         0.59684783]
 [0.54237288 0.         1.         0.         1.         0.
  1.         0.         0.21339671]
 [0.54237288 0.         1.         0.         1.         0.
  1.         0.         0.12023891]
 [0.22033898 1.         0.         0.         0.         1.
  1.         0.         0.04781412]
 [0.77966102 1.         0.         0.         1.         0.
  1.         0.         0.36819063]]
[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


'\nChú ý:\n - Việc mã hõa one-hot có thể khác nhau tùy theo cách quy ước.\n - Giá trị ở cột đầu tiên và cuối cùng của X_new là cố định\n - Mỗi dòng của mã hóa one hot ứng với một thuộc tính chỉ được phép có 1 số 1.\n'